// Momentum mod dark theme
"theme"
{
	"qt"
	{
		"Style"				"Fusion"
		"WindowText"  		"255 255 255"
		"Button"  			"79 79 79"
		"Text"  			"255 255 255"
		"BrightText"  		"200 0 0"
		"ButtonText"  		"255 255 255"
		"Base"  			"32 32 32"
		"Window"  			"50 50 50"
		"Highlight"  		"24 150 211"
		"HighlightedText" 	"32 32 32"
		"Link"  			"24 150 211"
		"AlternateBase" 	"79 79 79"
		"ToolTipBase"  		"255 255 255"
		"ToolTipText" 		"255 255 255"
	}
}
