// stripped down and posed version of "player/american_rifleman.mdl" with included gun and accurate bbox
// used for info_player_allies
$modelname "editor/american_rifleman.mdl"
$cdmaterials "models/player/american"
$cdmaterials "models/weapons/w_models/garand"

$surfaceprop flesh
$staticprop

$origin 0 0 0 270
$body studio "american_rifleman"
$sequence idle "american_rifleman"

$bbox -16 -16 0 16 16 72
