// stripped down and posed version of "player/german_rifleman.mdl" with included gun and accurate bbox
// used for info_player_axis
$modelname "editor/german_rifleman.mdl"
$cdmaterials "models/player/german"
$cdmaterials "models/weapons/w_models/k98"

$surfaceprop flesh
$staticprop

$origin 0 0 0 270
$body studio "german_rifleman"
$sequence idle "german_rifleman"

$bbox -16 -16 0 16 16 72
