
//********************************************************************************************
//AUTOGENERATED by main\portal2\staging\content\portal2\docs\ScriptProgs\dlc2\makenutlist.PRG
//********************************************************************************************



SceneTableLookup[-5500] <- "-5500"
//Welcome, test subject, it's Cave. Prime. From Earth One. I am speaking to you from across time and space! I am literally in the future! I am--Hold on... [off mic] What? [on mic] Alright, my assistant Greg tells me none of that's true. Got excited. You
SceneTable["-5500"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0100_caveprime_misc01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5501] <- "-5501"
//Cave here. Just so you know, this mic isn't two way. Can't hear a damn thing you're saying, so don't waste any oxygen trying to talk. [off mic] What? [on mic] My assistant Greg says some of these alternate Earths may not have oxygen. The air might be
SceneTable["-5501"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0200_caveprime_misc02.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5502] <- "-5502"
//Cave here. Man oh man. Wow. Greg's multiple universe theory was dicey, but you're pulling through with flying colors. We're all very proud of Greg. [pause]
SceneTable["-5502"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0300_caveprime_misc03.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5503] <- "-5503"
//Before we start testing today, let's have our mandatory minute of silence in honor of Earth's governing body, the Sentient Cloud. [throat clear] Starting now. [a pause] [coughing] [a longer pause] [more coughing] [still more pausing] Good, right. All ha
SceneTable["-5503"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0310_altcave_sentientcloud01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5504] <- "-5504"
//I've just been notified that one of our test subjects may have angered the Sentient Cloud by beginning testing early. Now, as you all know, the cloud has banned all camera technology--hates getting its picture taken. So this'll have to be on the honor
SceneTable["-5504"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0311_altcave_sentientcloud03.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5505] <- "-5505"
//Just a heads-up that the Cloud's still waiting. I don't think that thing's gonna go away, so somebody might wanna get out there.
SceneTable["-5505"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0312_altcave_sentientcloud04.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5506] <- "-5506"
//"No! No! It came in under the door! It's leeching off all my skin! Aghhhhh-" [click] Excerpt there from one of our safety videos. Grisly stuff, very informative. Somebody doesn't get out there soon we're gonna have to have a lottery, because believe me,
SceneTable["-5506"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0313_altcave_sentientcloud05.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5507] <- "-5507"
//Cave here. The real Cave. Greg's been crunching some numbers here on Earth Prime. Turns out, the likelihood of me being the only Cave who likes talking to test subjects is-- [off mic] What's the actual number, Greg? [on mic] Right. Zero. So tell you
SceneTable["-5507"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0400_caveprime_misc04.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5508] <- "-5508"
//Welcome, gentlemen, to Aperture Rituals. Astronauts, war heroes, olympians: you're here because of an ancient mating ritual etched in a monolith by the Elder Monks to forestall the end of days. So, who is ready to make love to a giant bird?
SceneTable["-5508"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0410_altcave_mating_ritual01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5509] <- "-5509"
//Cave Johnson here. Just wanna let the cafeteria staff know to lay off the soylent green. I'm holding a memo from the President, and it turns out that soylent green is... [paper rustling] let's see here... doubling in price. Now listen up: I don't care
SceneTable["-5509"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0420_altcave_soylent01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5510] <- "-5510"
//(tap dancing noises) Hey. It's Cave. Someone's not daaaancing. Come on. You know the law - testing IS NOT a dance exemption. Don't make me call the dance police.
SceneTable["-5510"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0430_altcave_dance_police01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5511] <- "-5511"
//Test subject, can you hear me? Congratulations! You are the world's first half-man, half-machine police officer! Well, first batch. There was a pretty big shootout. Bought all your caracasses off the mayor. Anyway, you should be proud to be a part of
SceneTable["-5511"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0440_altcave_robot_a_cop01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5512] <- "-5512"
//Come in, Robot-a-Cop! It's your chief. First: You're a damn good cop. Second: You're a loose cannon. Alright, that's probably enough motivation. Oh, before I forget! Greg tells me you might be getting some tragic flashbacks of your former life. Don't
SceneTable["-5512"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0450_altcave_robot_a_cop02.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5513] <- "-5513"
//Cave here. Chariots. Just a heads up: If it seems like you're walking faster than light, you're probably in a universe where light doesn't haul nearly as much ass as it does on Earth One. The lab boys say if you insist on walking faster than light, you
SceneTable["-5513"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0500_caveprime_misc05.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5514] <- "-5514"
//Welcome, test prisoner, to the Terra-Three penal science colony. Space criminals, political prisoners, exiled planetary leaders: You're here because the galaxy needed a place to put you, and this is it. So, who is ready to stay here until they die? Now,
SceneTable["-5514"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0510_altcave_penal_science01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5515] <- "-5515"
//Attention, test prisoners attempting to escape through the air ducts. I don't know what nonsense you learned on TV, but in real life, air ducts just go to the air conditioning unit. It's also pretty dusty, so if you've got asthma, chances are you're
SceneTable["-5515"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0520_altcave_penal_science02.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5516] <- "-5516"
//[throat clear] This thing on? I'm gonna be brief. Because I'm dying. Because I got shivved. A lot. I just wanna get it on record that using force fields for doors in a space prison is a bad idea.  You know what would have been better? Regular doors.
SceneTable["-5516"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0530_altcave_penal_science03.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5517] <- "-5517"
//Those of you who volunteered to be injected with homo sapien DNA, I've got some good news and some bad news: bad news is we're postponing those tests indefinitely. Good news is we've got a much better test for you: fighting an army of man-mantises. Pick
SceneTable["-5517"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0540_altcave_man_mantis01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5518] <- "-5518"
//It's come to my attention that over half of our test subjects have only recently awoken from extended relaxation and were unaware that we're testing in space. So there it is: No conspiracy. No twist. We're in a test satellite orbiting the Earth.
SceneTable["-5518"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0550_altcave_sat_of_love01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5519] <- "-5519"
//Looks like we just had to seal up Science Sphere Seven. Hull breach. Another adventure party smashed through the hull to learn the big mystery. Guess they were busy doing that instead of testing, because I've mentioned we're in space every half hour. By
SceneTable["-5519"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0551_altcave_sat_of_love02.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5520] <- "-5520"
//Aaaand another hull breach. Let's all give a big hand to the test subjects of Sphere Eighteen for bravely uncovering the company-wide conspiracy, which is that there's no air in space. Once again: We're in space. It's not a secret. I am sincerely
SceneTable["-5520"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0552_altcave_sat_of_love03.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5521] <- "-5521"
//Welcome, gentlemen, to the Aperture Hollow "Science Jungle". Tramps, hillbillies, drifters: you're here because you followed the hobo signs. So, who is ready to scrounge around for some science? Now, you already met one another on the boxcar over here,
SceneTable["-5521"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0560_altcave_hobo_king01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5522] <- "-5522"
//It's Cave. Greg's telling me the number of possible alternate universes is literally infinite. Maybe there's one where, I don't know, the Greeks won World War II. Just a heads up in case you get to a test chamber and find yourself surrounded by urns.
SceneTable["-5522"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0600_caveprime_misc06.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5523] <- "-5523"
//That shrieking voice you just heard is the lovely Blark-Barg, my assistant. She's the backbone of this facility. Sorry fellas, she's married -- to producing seeds that germinate and detach from her exoskeleton at high speeds in search of human hosts! We
SceneTable["-5523"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0610_altcave_blark_barg01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5524] <- "-5524"
//Hello, test subjects. Good news first: our telekinesis incubation program has been a huge success. Bad news: The candidate screening process was a lot less successful. Let me tell you, we picked a real bunch of smart alecs to give mind-powers to. You
SceneTable["-5524"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0620_altcave_head_exploding01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5525] <- "-5525"
//That's right everybody, it's that time of year again: Happy Birth Day. You know the rules, everybody at the government-mandated maximum age needs to report to an ethnological redundancy associate toot suite.  Looking through your files here--the
SceneTable["-5525"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0630_altcave_johnsons_run01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5526] <- "-5526"
//Cave Johnson, junior claims representative for Aperture Science here. Well, former junior claims representative. Just found out I got laid off. Well, I'll just sneak into their recording office and let everyone know our president, that bastard Doug
SceneTable["-5526"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0640_altcave_young_cave01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5527] <- "-5527"
//Cave Johnson here. The mantis men have officially taken over the facility. If you can still get out, get out now! They're (crunching noises) oh god, they're breaking through the barricades!
SceneTable["-5527"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0650_altcave_mantis_attack01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5528] <- "-5528"
//Cave Johnson here. I seeeee you. I seeee your little feet. I'm gonna cut off your hair and put in on your feet and eat your little hair and feet! Um yum yum yum yum!
SceneTable["-5528"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0660_altcave_creepy_cave01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5529] <- "-5529"
//Hey! Hey! What are you doing in here? Beat it. [off mic] Come on, Greg, I told you not to let your creepy kid in my office. No, I'm sorry Greg, but there's something wrong with that kid. [putting on creepy kid voice] "We'll test forever." Why's she
SceneTable["-5529"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0670_altcave_gregs_creepy_kid01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5530] <- "-5530"
//Chariots! Cave Johnson here, reminding you to fill out the paperwork for full payment once you're done testing. The check may seem exorbitant, but you deserve it. Chariots!
SceneTable["-5530"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0700_caveprime_misc07.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5531] <- "-5531"
//Chariots! It's Cave Johnson. If you get through this next room, you'll get a bonus. And that's on top of the bonus I gave you this morning. [laughing] Don't thank me, because you're the real boss. Why? Because you teach me something new every day.
SceneTable["-5531"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0701_caveprime_misc08.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5532] <- "-5532"
//This is Cave. PRIME. So apparently there's an alternate dimension Cave Johnson who just uses the word "chariots" for no reason.
SceneTable["-5532"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0702_caveprime_misc09.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5533] <- "-5533"
//Hello, test subject! Cave Johnson here, founder and CEO of Aperture Science: the best damn applied sciences company on Earth. How good is the science here? Get a load of this: I'm dead! Now, you're probably asking yourself, "Cave, how is that possible?
SceneTable["-5533"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0710_altcave_dead_cave01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5534] <- "-5534"
//Just a warning to you test subjects: Greg and the boys told me that the massive influx of information I'd receive when they transferred my consciousness into a stadium-sized super computer would turn me crazy. So, once again a warning: Greg and the boys
SceneTable["-5534"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0711_altcave_dead_cave02.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5535] <- "-5535"
//Cave again. Now, I'll admit, losing my body does have its drawbacks. But it's got its perks too! As a being of pure intellect, I've now got time to read the entire literary canon of the human race. Here I go! [BEEP] And I am done. [beat] [sigh] Continue
SceneTable["-5535"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0712_altcave_dead_cave03.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5536] <- "-5536"
//Pure Intellect Cave here. Not to brag, but while you were cat-assing that last test, I rewrote the collected works of everything ever. I figure,, if I gotta read this garbage for eternity, I may as well improve it. Next time you curl up with a
SceneTable["-5536"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0713_altcave_dead_cave04.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5537] <- "-5537"
//Here's a question for you: Who is not afraid of no ghosts? [beep] As of just now, every character in every book by Virginia Woolf. Man, those things were dull.
SceneTable["-5537"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0714_altcave_dead_cave05.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5538] <- "-5538"
//Cave again. What is the one thing that could never ever ever ever in a million years get boring? If you said "busting ghosts" tragically, you'd be wrong. I was almost all the way through the W's when the bloom came off that rose. Heathcliff was
SceneTable["-5538"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0715_altcave_dead_cave06.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5539] <- "-5539"
//I've been thinking: What if Greg was right? What if injecting my consciousness into a computer robbed me of an eternal reward? Spiritually speaking. [beep] Alright, I just read up on it. Stumbled on a book about a fella who lived thousands of years ago.
SceneTable["-5539"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0716_altcave_dead_cave07.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5540] <- "-5540"
//Unless... Aperture was the monster. Aperture and everybody inside it. Holy Hercules! I just thought of something. Keep testing. Or don't. Doesn't matter. I'll be back.
SceneTable["-5540"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0717_altcave_dead_cave08.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5541] <- "-5541"
//Whoa! Chariots chariots. For some reason, some of the audio was bleeding through in this universe. Don't know if you were catching the subtext there, but that computer Cave is crazy. So: Greg was right. As of now, we are cancelling the genetic lifeform
SceneTable["-5541"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0718_altcave_dead_cave09.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5542] <- "-5542"
//Welcome, gentlemen, to Aperture Paranormal. Magicians, witches, crystal healing doctors: you're here because you have scary powers and we want in on it. So: who is ready to draw some pentagrams? Now you already met one another on the cab ride over so
SceneTable["-5542"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0750_altcave_magic01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5543] <- "-5543"
//Cave Johnson again, just a heads up, you are currently in a tiny test chamber floating around in my bloodstream.  Remember, if you see a giant set of car keys, those are mine. Lab boys shrunk 'em part way down before I could stop 'em. No idea if
SceneTable["-5543"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0760_altcave_car_keys01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5544] <- "-5544"
//Hello, test subject. As you are no doubt aware, the President is being held hostage inside the giant super-prison on the floor of the Atlantic Ocean . Every science facility in America has been tasked with producing a Tough Guy capable of breaking into
SceneTable["-5544"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0765_altcave_supermaxlantis01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5545] <- "-5545"
//Quick update on all those pods we were finding in broom closets. Apparently some alien monster was body-snatching employees and spawning Communist replicas. The allegorical threat level on this one's through the roof. Actual threat level's pretty
SceneTable["-5545"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0770_altcave_body_snatchers01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5546] <- "-5546"
//[meowing cat noises - either real cat sounds or JK Simmons doing meowing sounds]
SceneTable["-5546"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0775_altcave_cat_johnson01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5547] <- "-5547"
//Cave Johnson, new owner and CEO of Black Mesa. That's right, you've been bought. First order of business, we're renaming you under the Aperture brand. I'm leaning towards Blappeture Mesa. Marketing boys think something else. So: Blappeture it is. Next,
SceneTable["-5547"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0780_altcave_blappeture_mesa01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5548] <- "-5548"
//Cave Johnson here. Just wanted to let you know that, after decades of research and testing, we have finally transformed into beings of pure light. Go team. Not exactly what we were after, of course, but in the ballpark. So let's keep testing, and maybe
SceneTable["-5548"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0785_altcave_pure_salt01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5549] <- "-5549"
//Chariot chariot. By the way, you can make a bit of a mess in these rooms if you want. Scuff your shoes or stick gum on the walls, because these alternate Cave Johnsons are really cheesing me off.
SceneTable["-5549"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0800_caveprime_misc10.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5550] <- "-5550"
//Cave Johnson here. Just a heads-up we've got an interverse security breach in one of the test areas. You all enjoyed a good chuckle at Cave's expense when I started monitoring for parallel universe invasions. You all tried to stop me when I tried to
SceneTable["-5550"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0810_altcave_invasion01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5551] <- "-5551"
//Would anyone like to know what the invaders from Earth-1 are up to inside our facility? I don't blame you - bet it'd be fascinating stuff. But we don't have any multiverse invasion monitoring equipment. Asked for it. Told it was stupid. Anyway, I hope
SceneTable["-5551"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0811_altcave_invasion02.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5552] <- "-5552"
//Just a quick update on the attack of the killer ants. Apparently they tried to commandeer the entirety of our nation's sugar reserves in Kentucky. Big firefight at Fort Sugar Knox. Edge-of-your-seat stuff. Anyway, that's as far as I made it through the
SceneTable["-5552"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0820_altcave_killer_ants01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5553] <- "-5553"
//[coughing] Hi Mister. It's Timmy. Doc says I ain't gonna pull through. But if you could just finish this test, I bet we could lick this thing. [coughing]
SceneTable["-5553"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0825_altcave_timmy01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5554] <- "-5554"
//Cavina Johnson here. It's come to my attention that one of you has sent a letter to the Supreme Council of Matriarchs accusing me of being a man. So, I want to assure both you and Gender Regulatory Committee that I am indeed one hundred percent all
SceneTable["-5554"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0830_altcave_cavina01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5555] <- "-5555"
//I sincerely hope you're not allergic to air. Our peanut dust ventilator broke in this wing, so the atmosphere is only 60 per cent peanut dust.
SceneTable["-5555"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_0840_altcave_peanut_air01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5556] <- "-5556"
//Hey. It's me. The real me. Uh, chariots chariots. Anyway, it appears the test chambers in our dimension are being tested on. Looks like another alternate universe Cave Johnson is using the same trick I am. If you see that one, punch him in the throat
SceneTable["-5556"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_1000_caveprime_darkintro01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5557] <- "-5557"
//Chariots chariots. We have a problem. That alternate Cave Johnson is using ALL our test chambers now. We have to take care of things here for a while, so you're on your own. Try to remember the tests so we can write it all down later.
SceneTable["-5557"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_1100_caveprime_darkintro02.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5558] <- "-5558"
//Aha! We've got you, you...wait, is that the real you? From our dimension? Ahhh. Chariots chariots. It's Cave. Seriously, of all the infinite alternate dimensions, you happen to wind up randomly in ours again? Okay, just get through this test and be VERY
SceneTable["-5558"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_1200_caveprime_darkintro03.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5559] <- "-5559"
//Hey. Chariots chariots. Just thought you should know, that sick boy from a couple of Earths ago? We kept monitoring that because, man, that was riveting. Anyway, he didn't make it. Good try, though. We were virtually all pulling for him.
SceneTable["-5559"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_1300_caveprime_darkintro06.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5560] <- "-5560"
//Chariots chariots dammit! Now we've got two testers here from another damn Earth! We had one of 'em cornered, then the other one just portaled him out of there, then they high-fived and went their separate ways. I'm gonna need you to test double quick
SceneTable["-5560"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_1400_caveprime_darkintro07.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5561] <- "-5561"
//Attention: Chariots chariots. There are at least six extra-dimensional testers here now, and to be honest, they're not even really testing anymore. They just all portaled in, made a human pyramid, ate my lunch and portaled out.
SceneTable["-5561"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_1500_caveprime_darkintro08.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5562] <- "-5562"
//Chariots char-look it's me. Apparently, this other Earth has portal guns that can make portals on anything. We've had guys just walking along and suddenly, a portal opens beneath them and they fall out of a wall. I'm thinking maybe we should just work
SceneTable["-5562"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_1600_caveprime_darkintro09.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5563] <- "-5563"
//Chariots chariots. Okay. Greg managed to contact the Cave Johnson who keeps sending testers here and we've agreed, no more testing in each other's dimensions. We'll get you back here ASAP.
SceneTable["-5563"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_1700_caveprime_darkintro10.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5564] <- "-5564"
//Hello, test subject. Just a heads-up that our research into stopping all the godzilla attacks on U.S. soil has been postponed indefinitely. Turns out it doesn't matter where you hatch a nest full of godzillas, they just make a beeline straight for
SceneTable["-5564"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_1710_altcave_eggshells01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5565] <- "-5565"
//Break one-nine. Big Box Cave Johnson here, hauling a freight shaker with a loada cold ones in the wagon down to Texarkana. I got twenty-eight hours to get this done, so I'm putting the hammer down. Anybody hearing this, shake the bushes and gimme your
SceneTable["-5565"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_1720_altcave_smokey_johnson01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5566] <- "-5566"
//Chariots chariots. Whoever this alternate Cave Johnson is, he's a jerk. Instead of sending us the apology fruit assortment he promised, he just sent a whole bunch of angry wasps. We'll find a way to get back at him, don't you worry. You keep testing,
SceneTable["-5566"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_1800_caveprime_darkintro11.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5567] <- "-5567"
//Chariots chariots. Okay, now the other Cave has sent a huge block of frozen urine. It's too big for us to get it out of the multiverse device, so we just have to let it melt until we can wedge it out. Incidentally, if you come across a dimension where
SceneTable["-5567"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_1900_caveprime_darkintro12.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5568] <- "-5568"
//Cave Johnson here. I need you to - [Dark Cave] Do not listen to this man. He's the other Cave Johnson. He's an impostor! [Cave Prime] You're the impostor, impostor! Chariots chariots! [Dark Cave] Oh, yeah? Chariots chariots chariots! Just keep testing.
SceneTable["-5568"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_2000_caveprime_conv_a01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5569] <- "-5569"
//All right. I think we shut down the impostor Cave's comlink. [Dark Cave] You'd like to think that, wouldn't you? [Cave Prime] Dammit! Stop imposting! [Dark Cave] Never! [Cave Prime] Oh, you stubborn, handsome devil.
SceneTable["-5569"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_2100_caveprime_conv_b01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5570] <- "-5570"
//It's come to my attention that there's a pair of sunglasses floating around this place that lets you see the subliminal propaganda we've painstakingly hidden on every visible surface. Look people, the reason  motivational propaganda works is because
SceneTable["-5570"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_2110_altcave_sunglasses01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5571] <- "-5571"
//[laughter] Oh, Dark Cave, you are the only one around here who gets me. I tell you, I haven't had a conversation this damn good since... Hold on, I gotta talk to the help. [tap tap tap] Hey, you. Chariots chariots. Keep testing.
SceneTable["-5571"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_2200_caveprime_conv_c01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5572] <- "-5572"
//Hey, Dark Cave. [Dark Cave] Cave Prime! As I live and breathe methane. [Cave Prime] Listen, do you have a Greg in your universe? You want one! [laughter] Greg, come back! I wouldn't send you to Dark Cave Earth. [whispered] I would. Greg is on the table.
SceneTable["-5572"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_2300_caveprime_conv_d01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5573] <- "-5573"
//Cave Johnson here. Just a reminder that the core goal of Aperture Gas-Finding Science is to find gas, so make sure you let us know if you see any. If we meet our quarterly gas-finding target, I promise you we will don our bondage gear, fuel our death
SceneTable["-5573"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_2305_altcave_gasoline01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5574] <- "-5574"
//[echoey] Hello, test subject. Echo. Echo. Welcome to your first test. I'm your overseer, Cave Johnson, and I think, if you keep testing, you might find something very interesting about this planet. [chuckle] [beat] It's me. I'm the planet. You live on
SceneTable["-5574"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_2310_altcave_planet_cave01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5575] <- "-5575"
//Chariots Chariots. According to Greg, theoretically, there's an Earth out there made entirely of money. Plus, since there's a infinite number of Earths, that means there's an infinite number of money planets. So I've done the math, and I figure the odds
SceneTable["-5575"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_2400_caveprime_moneyverse01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5576] <- "-5576"
//Chariots Chariots chariots. Dark Cave here. Listen, you find the moneyverse, you bring it to me. I'll take care of you. You want to be promoted to head of testing? Done. You want your asparagus rations doubled? I'll pull some strings. You want all the
SceneTable["-5576"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_2500_caveprime_moneyverse02.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5577] <- "-5577"
//Chariots chariots. Cave Prime here. I hear you've been brokering a deal with that other Cave. So here's what I want you to do: find your alternate self, steal his stuff, put in a box, and if there's a parking lot, walk the box out to it, because you're
SceneTable["-5577"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_2600_caveprime_moneyverse03.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5578] <- "-5578"
//Chariots chariots. Cave Johnson here. Alright. Greg's informed this is not the best time to fire you. But, if you ARE talking to that other Cave, let me just remind you who you work for. [Dark Cave] Chariots chariots chariots. And let me remind you
SceneTable["-5578"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_2700_caveprime_conv_e01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5579] <- "-5579"
//Cave Prime here. [Dark Cave] Dark Cave here. [Cave Prime] While you were busy driving a wedge between us with your bidding war, Dark Cave's test subject found two moneyverse. And we're gonna split 'em. So there's no reason to offload our testing to
SceneTable["-5579"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_2800_caveprime_conv_f01.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}

SceneTableLookup[-5580] <- "-5580"
//Hey Greg, it worked! Welcome back, test subject! Now get back to work. Just because we own a universe made of money, doesn't mean I'm made of money. Cave Johnson. We're done here.
SceneTable["-5580"] <-
{
	vcd=CreateSceneEntity("scenes/npc/cavejohnson/dlc2_2900_caveprime_moneyverse04.vcd"),
	char = "cavejohnson",
	postdelay = 0.00,
	predelay = 2.75,
	fires=[{entity="@glados",input="runscriptcode",parameter="DLC2_WriteBack()",delay=0.00}],
	next = null, noDingOff = true, noDingOn = true
}



//********************************************************************************************
//END OF AUTOGENERATED by main\portal2\staging\content\portal2\docs\ScriptProgs\dlc2\makenutlist.PRG
//********************************************************************************************

/*
mapID = GetMapIndexInPlayOrder();
If mapID is -1
	this map hasn’t been played before. 
If it’s -2
	it’s not a real map so don’t play any VO. 
Otherwise 
	the mapID is the (zero-based) number this map was played in the order. So 2 is the third map the users has played.


If the map hasn’t been played before, then:
	mapID = SetMapAsPlayed();

If mapID is < 0, bail.

Same deal for mapID here as if it had been found in the first call, (remember: zero-based).
*/

function DLC2_PlayEntryVO()
{
	local mapID = GetMapIndexInPlayOrder()
	local onID = GetNumMapsPlayed()
	printldebug(">>>>>DLC2 MAPID "+mapID)
	printldebug(">>>>>DLC2 ONID "+onID)
	if (mapID == -1)
	{
		printldebug(">>>>>DLC2 UNPLAYED MAP"+onID)
		GladosPlayVcd(-5500-onID)
	}
	else
	{
		if (mapID>=0)
		{
			printldebug(">>>>>DLC2 REPLAYING MAP "+mapID)
			GladosPlayVcd(-5500-mapID)
		} 
		else if (mapID == -2) // Added by TeamSpen210
		{
			printl("DLC2 SCRIPT OVERRIDE - PLAYING RANDOM LINE!");
			GladosPlayVcd(-5500-RandomInt(0,80));
		}
	}
}

function DLC2_WriteBack()
{
	printldebug("<><><><>DLC2_WriteBack")
	if (GetMapIndexInPlayOrder() == -1)
	{
		SetMapAsPlayed()
	}	
}

